### ISSUE TITLE
[FR] Support starting/stopping Azure MySQL server

### ISSUE THREAD

**Issue by claassen** [cloudfoundry/csb-brokerpak-azure#1]
**Is your feature request related to a problem? Please describe.**
We would like to be able to use the broker to start and stop Azure MySQL server instances in order to reduce costs.

https://docs.microsoft.com/en-us/azure/mysql/how-to-stop-start-server

**Describe the solution you'd like**
Open to any suggestions.

**Describe alternatives you've considered**
N/A

**Additional Context**
There does not seem to be a way to do this natively with Terraform, the only option I can see would be using local-exec provisioner with the az CLI embedded into the broker.

**Priority**
Low

**Platform** 
Azure

**Applicable Services**
csb-azure-mysql

**Comment by winnab** [comment]
Tracker story https://www.pivotaltracker.com/story/show/177645367

**Comment by blgm** [comment]
I'm going to close this because:
- it hasn't been done in over two years, so in reality it's not going to get done, so this issue is just noise
- the rationale is to reduce costs. The way to achieve that now would be to use a flexible/serverless database which is billed according to usage, rather than a system where App Developers have to remember to stop a database

If anyone has a different opinion, then please do speak up by re-opening this issue, or opening another one that references this issue
