### ISSUE TITLE
Azure Redis and Cosmo/MongoDB private endpoint unusable

### ISSUE THREAD

**Issue by drebake** [cloudfoundry/csb-brokerpak-azure#197]
**Describe the bug**
When creating Redis and Cosmos/MongoDB services using the private_endpoint_subnet_id and private_dns_zone_ids parameters, a private endpoint and private dns entry are created, but the binding information URI (cosmos/mongodb) and host (redis) are still pointing to the public fqdn and not the private endpoint.

So the communication then resolves to the public IP of the service and we are unable to use the private endpoint.

**To Reproduce**
1. Create a Redis or Cosmos/MongoDB service with the private_endpoint_subnet_id and private_dns_zone_ids parameters.
2. Bind your service
3. View binding information to get credhub  info.
4. Interogate credhub to get binding information.

**Expected behavior**
In the binding information for redis, the host should be the .privatelink.redis.cache.windows.net fqdn and not the .redis.cache.windows.net

In the binding information for the cosmos/mongodb, the URI should be to the .mongo.cosmos.azure.com and not the .mongo.cosmos.azure.com

If we are not using the .privatelink.redis.cache.windows.net or .privatelink.mongo.cosmo.azure.com, we are not communicating with the service using the private endpoint.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
We are using the cloud service broker for Azure version 1.2.3
Opsman: 2.10.26
TAS: 2.11.10

**Comment by rkoster** [comment]
Thanks for reporting this issue. The private endpoint properties were added in this PR: https://github.com/cloudfoundry/csb-brokerpak-azure/pull/33. It seems like the implementation might have been incomplete since I would have expected logic around the `host` output: https://github.com/cloudfoundry/csb-brokerpak-azure/blob/main/terraform/azure-redis/redis-provision.tf#L116 to make it private endpoint aware.

Since this feature came in through a community contribution we, unfortunately, won't be able to prioritize this anytime soon. However, we are more than happy to review a PR addressing this issue.

**Comment by drebake** [comment]
I will close this issue. After looking into the TLS errors we got when I replace the credhub credentials to use the .privatelink fqdn, I noticed we had TLS errors which made me dig more into the certificate errors. The .privatelink fqdn were not in the certificates SAN's. We then noticed that we had to forward DNS resolution of the  .mongo.cosmos.azure.com and .mongo.cosmos.azure.com to the Microsoft DNS.

With the privatelinks in place, the Microsoft DNS now resolve to the privatelink IP's and the certificates are working.
