### ISSUE TITLE
Is it possible to add Azure service bus in this broker?

### ISSUE THREAD

**Issue by amitgupta5888** [cloudfoundry/csb-brokerpak-azure#85]
Also is there a proper document to make some one understand how a new service can be added in the Azure BrokerPak.
If not, can someone please share some basic information as I am a bit lost here.

@erniebilling @blgm @claassen @sujitdmello

**Comment by blgm** [comment]
Hi @amitgupta5888, there is information about how to develop brokerpaks here: https://github.com/cloudfoundry-incubator/cloud-service-broker/tree/main/docs

This is an open source project that's principally contributed to by a team at VMware. You would be very welcome to contribute a pull request. But I should caution you that the maintainers have been slow to merge pull requests recently as we try to review them to make sure that changes are applicable to many users, rather than being applicable to only one specific situation. Having said that, this approach works for many.

Another approach that customers of VMware can request that the VMware team should add a feature on their behalf. Requests of that nature should be made via a VMware account team so that it's clear that they are commercial requests.

**Comment by pivotal-marcela-campo** [comment]
Closing this issue as there hasn't been any activity. If you still want this feature we are happy to review a PR.
